GitHub: Init guidelines documentation
Kiki-s-homebox/webshop-frontend pull request #2
Opened 2023-09-29 18:27 UTC by g4ndalfTheCreator

Documentation about GitHub guidelines and processes.

2023-09-30 11:05 UTC, g4ndalfTheCreator commented
Comment here your thoughts and improvement ideas for this document!

2023-09-30 12:39 UTC, cxanng commented on GIT-GUIDELINES.md
> +  git rebase main
This is okay. However, I would prefer interactive rebasing with `--i` tag, which makes it a bit easier to see and pick or squash commits before merging. For example, we should squash those commits like "Refactor code" or "Fix typos", etc.

2023-09-30 12:42 UTC, cxanng commented on GIT-GUIDELINES.md
> +  Avoid: "Fixed stuff"
In cases where you realize there are typos or small details that you are not happy with but the changes are too small for creating another commit, you can add the changes and "recreate" the previous commit by 
`git commit --amend`
`git push --force-with-lease`

2023-09-30 12:43 UTC, cxanng commented on GIT-GUIDELINES.md
> +  git rebase main
And remember to use the tag `--force-with-lease` to push after rebasing

2023-09-30 12:46 UTC, g4ndalfTheCreator commented on GIT-GUIDELINES.md
> +  git rebase main
You are right about this. I will add the -i flag as recommendation!

2023-09-30 12:49 UTC, g4ndalfTheCreator commented on GIT-GUIDELINES.md
> +  Avoid: "Fixed stuff"
At the moment I propose that we squash and the commits on PR. This means that commit sizes do not matter in the main since all commits will be squashed to make version history in main to look cleaner

2023-09-30 12:54 UTC, cxanng commented on GIT-GUIDELINES.md
> +  Avoid: "Fixed stuff"
That's okay too. This is just for the feature branch commits to help with the review process.

2023-09-30 12:57 UTC, g4ndalfTheCreator commented on GIT-GUIDELINES.md
> +  Avoid: "Fixed stuff"
I will add these suggestions to the guide to instruct people to do this if they want to, since it may help reviewing the code.

2023-09-30 13:08 UTC, gaurabmahat submitted a review, later dismissed
I agree with these Guidelines.

2023-09-30 16:36 UTC, essituominen submitted a review, later dismissed

2023-09-30 19:38 UTC, cxanng approved these changes
Looks good to me.

2023-10-01 06:01 UTC, Korstoliini submitted a review, later dismissed

2023-10-01 11:07 UTC, RoopeSalento submitted a review, later dismissed
Looks good to me.
I approve these guidelines

2023-10-01 16:32 UTC, nhitran-tuni approved these changes

2023-10-01 16:38 UTC, nhitran-tuni requested changes
Should you add a section for running pre-commit hook that I mentioned in the PR I've just created?

2023-10-07 21:57 UTC, g4ndalfTheCreator reviewed
Added requested guidelines about npm run precommit

2023-10-09 16:58 UTC, nhitran-tuni approved these changes

2023-10-10 19:58 UTC, merged